// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoabxbsvcrmzlvkxqksb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYWJ4YnN2Y3Jtemx2a3hxa3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NjczODAsImV4cCI6MjA5MTI0MzM4MH0.ktyiZ6waUBAPPcyNes420cI8KHdq1kOMLiTshaeGsuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});